<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Gaming Mouse',
                'sku' => 'ELEC-001',
                'category' => 'Electronics',
                'stock' => 80,
                'image' => 'https://picsum.photos/600/400?random=1',
                'weight' => 0.15,
                'dimensions' => '12x7x4 cm',
                'meta' => json_encode(['color' => 'black', 'dpi' => '16000']),
                'description' => 'RGB gaming mouse with programmable buttons.',
                'price' => 4079.00,
            ],
            [
                'name' => 'Mechanical Keyboard',
                'sku' => 'ELEC-002',
                'category' => 'Electronics',
                'stock' => 50,
                'image' => 'https://picsum.photos/600/400?random=2',
                'weight' => 0.90,
                'dimensions' => '45x15x4 cm',
                'meta' => json_encode(['switch' => 'blue', 'backlight' => true]),
                'description' => 'Mechanical keyboard with RGB lighting.',
                'price' => 9179.00,
            ],
            [
                'name' => 'USB-C Charger',
                'sku' => 'ELEC-003',
                'category' => 'Electronics',
                'stock' => 120,
                'image' => 'https://picsum.photos/600/400?random=3',
                'weight' => 0.20,
                'dimensions' => '8x5x3 cm',
                'meta' => json_encode(['power' => '65W']),
                'description' => 'Fast charging USB-C adapter.',
                'price' => 3059.00,
            ],
            [
                'name' => 'Smart Watch',
                'sku' => 'ELEC-004',
                'category' => 'Electronics',
                'stock' => 40,
                'image' => 'https://picsum.photos/600/400?random=4',
                'weight' => 0.08,
                'dimensions' => '5x5x2 cm',
                'meta' => json_encode(['battery' => '7 days']),
                'description' => 'Fitness tracking smartwatch.',
                'price' => 15299.00,
            ],
            [
                'name' => 'Bluetooth Speaker',
                'sku' => 'ELEC-005',
                'category' => 'Electronics',
                'stock' => 70,
                'image' => 'https://picsum.photos/600/400?random=5',
                'weight' => 0.60,
                'dimensions' => '20x8x8 cm',
                'meta' => json_encode(['battery' => '12h']),
                'description' => 'Portable Bluetooth speaker.',
                'price' => 6119.00,
            ],
            [
                'name' => 'Laptop Sleeve',
                'sku' => 'ACC-001',
                'category' => 'Accessories',
                'stock' => 90,
                'image' => 'https://picsum.photos/600/400?random=6',
                'weight' => 0.30,
                'dimensions' => '38x28x2 cm',
                'meta' => json_encode(['size' => '15-inch']),
                'description' => 'Protective laptop sleeve.',
                'price' => 2124.00,
            ],
            [
                'name' => 'Leather Wallet',
                'sku' => 'ACC-002',
                'category' => 'Accessories',
                'stock' => 150,
                'image' => 'https://picsum.photos/600/400?random=7',
                'weight' => 0.12,
                'dimensions' => '12x10x2 cm',
                'meta' => json_encode(['material' => 'genuine leather']),
                'description' => 'Premium leather wallet.',
                'price' => 2974.00,
            ],
            [
                'name' => 'Sunglasses',
                'sku' => 'ACC-003',
                'category' => 'Accessories',
                'stock' => 100,
                'image' => 'https://picsum.photos/600/400?random=8',
                'weight' => 0.10,
                'dimensions' => '15x5x5 cm',
                'meta' => json_encode(['uv_protection' => 'UV400']),
                'description' => 'Stylish UV protection sunglasses.',
                'price' => 1699.00,
            ],
            [
                'name' => 'Baseball Cap',
                'sku' => 'APP-001',
                'category' => 'Apparel',
                'stock' => 130,
                'image' => 'https://picsum.photos/600/400?random=9',
                'weight' => 0.15,
                'dimensions' => '25x20x10 cm',
                'meta' => json_encode(['color' => 'navy']),
                'description' => 'Adjustable baseball cap.',
                'price' => 1274.00,
            ],
            [
                'name' => 'Hoodie',
                'sku' => 'APP-002',
                'category' => 'Apparel',
                'stock' => 75,
                'image' => 'https://picsum.photos/600/400?random=10',
                'weight' => 0.65,
                'dimensions' => '40x35x5 cm',
                'meta' => json_encode(['size' => 'L', 'material' => 'cotton']),
                'description' => 'Warm cotton hoodie.',
                'price' => 3399.00,
            ],
            [
                'name' => 'Polo Shirt',
                'sku' => 'APP-003',
                'category' => 'Apparel',
                'stock' => 95,
                'image' => 'https://picsum.photos/600/400?random=11',
                'weight' => 0.30,
                'dimensions' => '30x25x2 cm',
                'meta' => json_encode(['color' => 'black']),
                'description' => 'Classic polo shirt.',
                'price' => 2549.00,
            ],
            [
                'name' => 'Denim Jeans',
                'sku' => 'APP-004',
                'category' => 'Apparel',
                'stock' => 85,
                'image' => 'https://picsum.photos/600/400?random=12',
                'weight' => 0.75,
                'dimensions' => '40x30x4 cm',
                'meta' => json_encode(['fit' => 'slim']),
                'description' => 'Comfortable slim-fit jeans.',
                'price' => 4249.00,
            ],
            [
                'name' => 'Sports Shorts',
                'sku' => 'APP-005',
                'category' => 'Apparel',
                'stock' => 120,
                'image' => 'https://picsum.photos/600/400?random=13',
                'weight' => 0.22,
                'dimensions' => '25x20x2 cm',
                'meta' => json_encode(['material' => 'polyester']),
                'description' => 'Lightweight sports shorts.',
                'price' => 1699.00,
            ],
            [
                'name' => 'Yoga Mat',
                'sku' => 'FIT-001',
                'category' => 'Fitness',
                'stock' => 60,
                'image' => 'https://picsum.photos/600/400?random=14',
                'weight' => 1.10,
                'dimensions' => '180x60x1 cm',
                'meta' => json_encode(['thickness' => '10mm']),
                'description' => 'Non-slip yoga mat.',
                'price' => 2124.00,
            ],
            [
                'name' => 'Dumbbell Set',
                'sku' => 'FIT-002',
                'category' => 'Fitness',
                'stock' => 30,
                'image' => 'https://picsum.photos/600/400?random=15',
                'weight' => 10.00,
                'dimensions' => '30x20x15 cm',
                'meta' => json_encode(['weight' => '10kg']),
                'description' => 'Pair of adjustable dumbbells.',
                'price' => 6799.00,
            ],
            [
                'name' => 'Resistance Bands',
                'sku' => 'FIT-003',
                'category' => 'Fitness',
                'stock' => 90,
                'image' => 'https://picsum.photos/600/400?random=16',
                'weight' => 0.45,
                'dimensions' => '25x15x5 cm',
                'meta' => json_encode(['levels' => '5']),
                'description' => 'Resistance training bands.',
                'price' => 1274.00,
            ],
            [
                'name' => 'Protein Shaker',
                'sku' => 'FIT-004',
                'category' => 'Fitness',
                'stock' => 110,
                'image' => 'https://picsum.photos/600/400?random=17',
                'weight' => 0.18,
                'dimensions' => '10x10x20 cm',
                'meta' => json_encode(['capacity' => '700ml']),
                'description' => 'Leakproof protein shaker.',
                'price' => 849.00,
            ],
            [
                'name' => 'Desk Lamp',
                'sku' => 'HOME-001',
                'category' => 'Home',
                'stock' => 55,
                'image' => 'https://picsum.photos/600/400?random=18',
                'weight' => 0.90,
                'dimensions' => '40x15x15 cm',
                'meta' => json_encode(['led' => true]),
                'description' => 'LED desk lamp.',
                'price' => 2974.00,
            ],
            [
                'name' => 'Wall Clock',
                'sku' => 'HOME-002',
                'category' => 'Home',
                'stock' => 65,
                'image' => 'https://picsum.photos/600/400?random=19',
                'weight' => 0.80,
                'dimensions' => '30x30x5 cm',
                'meta' => json_encode(['color' => 'white']),
                'description' => 'Modern wall clock.',
                'price' => 1699.00,
            ],
            [
                'name' => 'Throw Pillow',
                'sku' => 'HOME-003',
                'category' => 'Home',
                'stock' => 100,
                'image' => 'https://picsum.photos/600/400?random=20',
                'weight' => 0.40,
                'dimensions' => '45x45x10 cm',
                'meta' => json_encode(['color' => 'grey']),
                'description' => 'Decorative throw pillow.',
                'price' => 1104.00,
            ],
            [
                'name' => 'Bed Sheet Set',
                'sku' => 'HOME-004',
                'category' => 'Home',
                'stock' => 70,
                'image' => 'https://picsum.photos/600/400?random=21',
                'weight' => 1.20,
                'dimensions' => '35x25x10 cm',
                'meta' => json_encode(['size' => 'queen']),
                'description' => 'Soft bed sheet set.',
                'price' => 3399.00,
            ],
            [
                'name' => 'Cookware Set',
                'sku' => 'HOME-005',
                'category' => 'Home',
                'stock' => 25,
                'image' => 'https://picsum.photos/600/400?random=22',
                'weight' => 4.50,
                'dimensions' => '50x35x25 cm',
                'meta' => json_encode(['pieces' => 10]),
                'description' => 'Non-stick cookware set.',
                'price' => 8499.00,
            ],
            [
                'name' => 'Office Chair',
                'sku' => 'FURN-001',
                'category' => 'Furniture',
                'stock' => 20,
                'image' => 'https://picsum.photos/600/400?random=23',
                'weight' => 12.50,
                'dimensions' => '70x70x120 cm',
                'meta' => json_encode(['ergonomic' => true]),
                'description' => 'Ergonomic office chair.',
                'price' => 22099.00,
            ],
            [
                'name' => 'Study Desk',
                'sku' => 'FURN-002',
                'category' => 'Furniture',
                'stock' => 15,
                'image' => 'https://picsum.photos/600/400?random=24',
                'weight' => 18.00,
                'dimensions' => '120x60x75 cm',
                'meta' => json_encode(['material' => 'wood']),
                'description' => 'Wooden study desk.',
                'price' => 16574.00,
            ],
            [
                'name' => 'Bookshelf',
                'sku' => 'FURN-003',
                'category' => 'Furniture',
                'stock' => 10,
                'image' => 'https://picsum.photos/600/400?random=25',
                'weight' => 22.00,
                'dimensions' => '80x30x180 cm',
                'meta' => json_encode(['shelves' => 5]),
                'description' => '5-tier bookshelf.',
                'price' => 19889.00,
            ],
            [
                'name' => 'Power Bank',
                'sku' => 'ELEC-006',
                'category' => 'Electronics',
                'stock' => 90,
                'image' => 'https://picsum.photos/600/400?random=26',
                'weight' => 0.35,
                'dimensions' => '15x8x2 cm',
                'meta' => json_encode(['capacity' => '20000mAh']),
                'description' => 'High-capacity power bank.',
                'price' => 4589.00,
            ],
            [
                'name' => 'Webcam',
                'sku' => 'ELEC-007',
                'category' => 'Electronics',
                'stock' => 40,
                'image' => 'https://picsum.photos/600/400?random=27',
                'weight' => 0.18,
                'dimensions' => '8x5x5 cm',
                'meta' => json_encode(['resolution' => '1080p']),
                'description' => 'Full HD webcam.',
                'price' => 5099.00,
            ],
            [
                'name' => 'Monitor Stand',
                'sku' => 'ELEC-008',
                'category' => 'Electronics',
                'stock' => 45,
                'image' => 'https://picsum.photos/600/400?random=28',
                'weight' => 2.50,
                'dimensions' => '60x25x10 cm',
                'meta' => json_encode(['adjustable' => true]),
                'description' => 'Adjustable monitor stand.',
                'price' => 3059.00,
            ],
            [
                'name' => 'Travel Bag',
                'sku' => 'BAG-001',
                'category' => 'Bags',
                'stock' => 55,
                'image' => 'https://picsum.photos/600/400?random=29',
                'weight' => 1.10,
                'dimensions' => '55x30x25 cm',
                'meta' => json_encode(['capacity' => '40L']),
                'description' => 'Large travel duffel bag.',
                'price' => 5099.00,
            ],
            [
                'name' => 'Laptop Backpack',
                'sku' => 'BAG-002',
                'category' => 'Bags',
                'stock' => 70,
                'image' => 'https://picsum.photos/600/400?random=30',
                'weight' => 0.90,
                'dimensions' => '45x30x20 cm',
                'meta' => json_encode(['fits' => '15-inch']),
                'description' => 'Laptop backpack with USB port.',
                'price' => 4674.00,
            ],
            [
                'name' => 'Crossbody Bag',
                'sku' => 'BAG-003',
                'category' => 'Bags',
                'stock' => 90,
                'image' => 'https://picsum.photos/600/400?random=31',
                'weight' => 0.45,
                'dimensions' => '25x20x8 cm',
                'meta' => json_encode(['color' => 'brown']),
                'description' => 'Compact crossbody bag.',
                'price' => 2549.00,
            ],
            [
                'name' => 'Water Bottle',
                'sku' => 'FIT-005',
                'category' => 'Fitness',
                'stock' => 140,
                'image' => 'https://picsum.photos/600/400?random=32',
                'weight' => 0.25,
                'dimensions' => '8x8x25 cm',
                'meta' => json_encode(['capacity' => '1L']),
                'description' => 'Reusable water bottle.',
                'price' => 1104.00,
            ],
            [
                'name' => 'Jump Rope',
                'sku' => 'FIT-006',
                'category' => 'Fitness',
                'stock' => 110,
                'image' => 'https://picsum.photos/600/400?random=33',
                'weight' => 0.20,
                'dimensions' => '20x15x5 cm',
                'meta' => json_encode(['adjustable' => true]),
                'description' => 'Speed jump rope.',
                'price' => 849.00,
            ],
            [
                'name' => 'Camping Tent',
                'sku' => 'OUT-001',
                'category' => 'Outdoor',
                'stock' => 15,
                'image' => 'https://picsum.photos/600/400?random=34',
                'weight' => 3.50,
                'dimensions' => '60x20x20 cm',
                'meta' => json_encode(['capacity' => '4-person']),
                'description' => 'Waterproof camping tent.',
                'price' => 11049.00,
            ],
            [
                'name' => 'Sleeping Bag',
                'sku' => 'OUT-002',
                'category' => 'Outdoor',
                'stock' => 25,
                'image' => 'https://picsum.photos/600/400?random=35',
                'weight' => 1.80,
                'dimensions' => '40x25x25 cm',
                'meta' => json_encode(['temperature' => '-5C']),
                'description' => 'Warm sleeping bag.',
                'price' => 5949.00,
            ],
            [
                'name' => 'Flashlight',
                'sku' => 'OUT-003',
                'category' => 'Outdoor',
                'stock' => 85,
                'image' => 'https://picsum.photos/600/400?random=36',
                'weight' => 0.30,
                'dimensions' => '20x5x5 cm',
                'meta' => json_encode(['battery' => 'rechargeable']),
                'description' => 'LED rechargeable flashlight.',
                'price' => 2124.00,
            ],
            [
                'name' => 'Garden Hose',
                'sku' => 'HOME-006',
                'category' => 'Home',
                'stock' => 40,
                'image' => 'https://picsum.photos/600/400?random=37',
                'weight' => 2.50,
                'dimensions' => '30x30x10 cm',
                'meta' => json_encode(['length' => '30m']),
                'description' => 'Flexible garden hose.',
                'price' => 2974.00,
            ],
            [
                'name' => 'Plant Pot',
                'sku' => 'HOME-007',
                'category' => 'Home',
                'stock' => 120,
                'image' => 'https://picsum.photos/600/400?random=38',
                'weight' => 0.60,
                'dimensions' => '20x20x18 cm',
                'meta' => json_encode(['material' => 'ceramic']),
                'description' => 'Decorative ceramic pot.',
                'price' => 1274.00,
            ],
            [
                'name' => 'Air Fryer',
                'sku' => 'HOME-008',
                'category' => 'Home',
                'stock' => 20,
                'image' => 'https://picsum.photos/600/400?random=39',
                'weight' => 4.20,
                'dimensions' => '35x35x40 cm',
                'meta' => json_encode(['capacity' => '5L']),
                'description' => 'Healthy cooking air fryer.',
                'price' => 10199.00,
            ],
            [
                'name' => 'Electric Kettle',
                'sku' => 'HOME-009',
                'category' => 'Home',
                'stock' => 50,
                'image' => 'https://picsum.photos/600/400?random=40',
                'weight' => 0.95,
                'dimensions' => '22x18x25 cm',
                'meta' => json_encode(['capacity' => '1.8L']),
                'description' => 'Fast boiling electric kettle.',
                'price' => 3399.00,
            ],
            [
                'name' => 'Table Fan',
                'sku' => 'HOME-010',
                'category' => 'Home',
                'stock' => 35,
                'image' => 'https://picsum.photos/600/400?random=41',
                'weight' => 2.80,
                'dimensions' => '40x25x50 cm',
                'meta' => json_encode(['speed_levels' => 3]),
                'description' => 'Portable table fan.',
                'price' => 4249.00,
            ],
            [
                'name' => 'Smartphone Stand',
                'sku' => 'ACC-004',
                'category' => 'Accessories',
                'stock' => 150,
                'image' => 'https://picsum.photos/600/400?random=42',
                'weight' => 0.10,
                'dimensions' => '12x8x2 cm',
                'meta' => json_encode(['foldable' => true]),
                'description' => 'Adjustable phone stand.',
                'price' => 764.00,
            ],
            [
                'name' => 'Wireless Mouse',
                'sku' => 'ELEC-009',
                'category' => 'Electronics',
                'stock' => 90,
                'image' => 'https://picsum.photos/600/400?random=43',
                'weight' => 0.12,
                'dimensions' => '11x6x4 cm',
                'meta' => json_encode(['dpi' => '2400']),
                'description' => 'Wireless optical mouse.',
                'price' => 2039.00,
            ],
            [
                'name' => 'HDMI Cable',
                'sku' => 'ELEC-010',
                'category' => 'Electronics',
                'stock' => 180,
                'image' => 'https://picsum.photos/600/400?random=44',
                'weight' => 0.20,
                'dimensions' => '15x15x2 cm',
                'meta' => json_encode(['length' => '2m']),
                'description' => 'High-speed HDMI cable.',
                'price' => 1223.00,
            ],
            [
                'name' => 'Portable SSD',
                'sku' => 'ELEC-011',
                'category' => 'Electronics',
                'stock' => 35,
                'image' => 'https://picsum.photos/600/400?random=45',
                'weight' => 0.10,
                'dimensions' => '10x6x1 cm',
                'meta' => json_encode(['storage' => '1TB']),
                'description' => 'External portable SSD.',
                'price' => 10199.00,
            ],
            [
                'name' => 'Graphic Tablet',
                'sku' => 'ELEC-012',
                'category' => 'Electronics',
                'stock' => 18,
                'image' => 'https://picsum.photos/600/400?random=46',
                'weight' => 0.70,
                'dimensions' => '35x22x1 cm',
                'meta' => json_encode(['active_area' => '10 inch']),
                'description' => 'Digital drawing tablet.',
                'price' => 9179.00,
            ],
            [
                'name' => 'Drone Camera',
                'sku' => 'ELEC-013',
                'category' => 'Electronics',
                'stock' => 8,
                'image' => 'https://picsum.photos/600/400?random=47',
                'weight' => 0.95,
                'dimensions' => '25x25x10 cm',
                'meta' => json_encode(['camera' => '4K']),
                'description' => 'Compact aerial drone camera.',
                'price' => 30599.00,
            ],
            [
                'name' => 'Action Camera',
                'sku' => 'ELEC-014',
                'category' => 'Electronics',
                'stock' => 25,
                'image' => 'https://picsum.photos/600/400?random=48',
                'weight' => 0.20,
                'dimensions' => '7x5x4 cm',
                'meta' => json_encode(['resolution' => '4K']),
                'description' => 'Waterproof action camera.',
                'price' => 16319.00,
            ],
        ];

        Product::upsert(
            $products,
            ['sku'],
            ['name', 'category', 'stock', 'image', 'weight', 'dimensions', 'meta', 'description', 'price']
        );
    }
}
